version: '2'
services:
  app:
    container_name: hello-api
    restart: always
    build: .
    environment:
        - SERVER_PORT=3000
        - DB_URL=mongodb://mongo:27017/hello-app
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
